trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    git submodule init
    git submodule update
  displayName: Initialize submodule

- script: choco install docfx --version 2.45
  displayName: Install DocFX
  
- task: PowerShell@2
  displayName: Build
  inputs:
    filePath: 'build.ps1'

- task: PublishBuildArtifacts@1
  displayName: 'Publish _site artifact'
  inputs:
    PathtoPublish: 'doc/_site'
    ArtifactName: 'Site'
    publishLocation: 'Container'