trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    git submodule init
    git submodule update
  displayName: Initialize submodule
- task: PowerShell@2
  displayName: Build
  inputs:
    filePath: 'build.ps1'
    failOnStderr: true